on:
  push:
   
    branches:
      - master



jobs:
  build:
    
    runs-on: ubuntu-latest 
    
    steps:
      - name: "testing github actions"
        run: pwd
      - name: "testing printing"
        run: echo ahmed
      - name: "printing folder contents Before"
        run: ls
      - users: actions/checkout@v3
      - name: "printing folder contents After"
        run: ls
